name: EMS BACKEND - Build and run tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build_and_test:
        name: Build and run unit tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x, 18.x]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install ems-db dependencies
              working-directory: ./ems-db
              run: npm ci
            - name: Run ems-db unit tests
              working-directory: ./ems-db
              run: npm run test:ci
            - name: Install ems-api dependencies
              working-directory: ./ems-api
              run: npm ci
            - name: Run ems-api unit tests
              working-directory: ./ems-api
              run: npm run test:ci
